//home
export const REQUEST_NOT_AUTHORIZED = 'HOME_LIST_REQUEST';
export const HOME_LIST_REQUEST = 'HOME_LIST_REQUEST';
export const HOME_LIST_REQUEST_SUCCESS = 'HOME_LIST_REQUEST_SUCCESS';
export const HOME_LIST_REQUEST_FAILED = 'HOME_LIST_REQUEST_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const LOGOUT_REQUEST_INIT = 'LOGOUT_REQUEST_INIT';
