export const fonts = {
  FONTSIZE_XTRA_SMALL: 10,
  FONTSIZE_SMALL: 11,
  FONTSIZE_NORMAL: 12,
  FONTSIZE_MEDIUM: 13,
  FONTSIZE_LARGE: 14,
  FONTSIZE_XTRA_LARGE: 15,
  FONTSIZE_XX_LARGE: 17,
  FONTSIZE_HEADING: 20,
  FONTSIZE_OTP: 14,
};
