platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ColearnMobile' do
  # Pods for ColearnMobile
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBColearnMobileNativeSpec', :path => "../node_modules/react-native/Libraries/FBColearnMobileNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'ColearnMobile', :path => '../node_modules/react-native/'
  pod 'ColearnMobile-Core', :path => '../node_modules/react-native/'
  pod 'ColearnMobile-CoreModules', :path => '../node_modules/react-native/ColearnMobile/CoreModules'
  pod 'ColearnMobile-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'ColearnMobile-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'ColearnMobile-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'ColearnMobile-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'ColearnMobile-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'ColearnMobile-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'ColearnMobile-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'ColearnMobile-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'ColearnMobile-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'ColearnMobile-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'ColearnMobile-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'ColearnMobile-cxxreact', :path => '../node_modules/react-native/ColearnMobileCommon/cxxreact'
  pod 'ColearnMobile-jsi', :path => '../node_modules/react-native/ColearnMobileCommon/jsi'
  pod 'ColearnMobile-jsiexecutor', :path => '../node_modules/react-native/ColearnMobileCommon/jsiexecutor'
  pod 'ColearnMobile-jsinspector', :path => '../node_modules/react-native/ColearnMobileCommon/jsinspector'
  pod 'ColearnMobileCommon/jscallinvoker', :path => "../node_modules/react-native/ColearnMobileCommon"
  pod 'ColearnMobileCommon/turbomodule/core', :path => "../node_modules/react-native/ColearnMobileCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ColearnMobileCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ColearnMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'ColearnMobile-tvOS' do
  # Pods for ColearnMobile-tvOS

  target 'ColearnMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
